/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Connections */
        get: operations["read_connections_api_v1_connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_api_v1_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/code-host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Code Host
         * @description Link the installation of the Pono app on the person's account: no key is asked (FR-010).
         */
        post: operations["connect_code_host_api_v1_connections_code_host_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_api_v1_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Health */
        get: operations["read_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Forget Chat */
        delete: operations["forget_chat_api_v1_me_chat_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/chat-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Chat
         * @description A one-time link that opens the chat; starting it lets the service find the chat (D-015).
         */
        post: operations["start_chat_api_v1_me_chat_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/chat-link/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Chat */
        post: operations["confirm_chat_api_v1_me_chat_link_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Choose Alert Address
         * @description Where quota alerts go when the code host keeps the person's address private (FR-025).
         */
        put: operations["choose_alert_address_api_v1_me_email_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose Locale */
        put: operations["choose_locale_api_v1_me_locale_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Workshop */
        get: operations["read_workshop_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project */
        get: operations["read_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Journal */
        get: operations["read_journal_api_v1_projects__project_id__journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/manifest-proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Manifest Proposal
         * @description Propose a manifest again after the person closed the previous proposal.
         */
        post: operations["request_manifest_proposal_api_v1_projects__project_id__manifest_proposal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/protection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Protect */
        post: operations["protect_api_v1_projects__project_id__protection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Refresh
         * @description Queue an immediate reading (FR-022). A foreign project is unknown: 404, never 403.
         */
        post: operations["request_refresh_api_v1_projects__project_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Releases */
        get: operations["read_releases_api_v1_projects__project_id__releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/releases/{release_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Only a person's session reaches this route: no key, no agent token exists (FR-011).
         */
        post: operations["approve_api_v1_projects__project_id__releases__release_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/releases/{release_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Release Evaluation */
        post: operations["request_release_evaluation_api_v1_projects__project_id__releases__release_id__evaluation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback */
        post: operations["rollback_api_v1_projects__project_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Repositories */
        get: operations["read_repositories_api_v1_repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertAddress */
        AlertAddress: {
            /** Email */
            email: string;
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /**
             * Headsha
             * @description The exact commit the person saw.
             */
            headSha: string;
        };
        /** ChatLink */
        ChatLink: {
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /**
             * Url
             * @description Opens the chat with the one-time code.
             */
            url: string;
        };
        /** Connection */
        Connection: {
            /** Externalref */
            externalRef: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "code_host" | "hosting" | "database";
            /** Provider */
            provider: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "expired" | "revoked";
            /**
             * Statuscheckedat
             * Format: date-time
             */
            statusCheckedAt: string;
        };
        /** ConnectionRequest */
        ConnectionRequest: {
            /**
             * Authorization
             * Format: password
             * @description Provider-issued authorization; stored encrypted, never returned.
             */
            authorization: string;
            /**
             * Endpoint
             * @description Base URL of a self-hosted provider.
             */
            endpoint?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "hosting" | "database";
            /** Provider */
            provider: string;
        };
        /** Deployment */
        Deployment: {
            /** Author */
            author: string | null;
            /** Commitsha */
            commitSha: string | null;
            /**
             * Environmentkind
             * @enum {string}
             */
            environmentKind: "production" | "preview" | "development";
            /** Finishedat */
            finishedAt: string | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "building" | "succeeded" | "failed" | "cancelled";
        };
        /** Environment */
        Environment: {
            /** Branch */
            branch: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "production" | "preview" | "development";
            /** Linkcheckedat */
            linkCheckedAt: string | null;
            /**
             * Linkstatus
             * @enum {string}
             */
            linkStatus: "up" | "down" | "unknown" | "missing";
            /** Openedat */
            openedAt: string | null;
            /** Provider */
            provider: string | null;
            /**
             * Resourcestatus
             * @enum {string}
             */
            resourceStatus: "found" | "missing" | "unknown";
            /** Url */
            url: string | null;
        };
        /** Finding */
        Finding: {
            /** Code */
            code: string;
            /** File */
            file?: string | null;
            /** Line */
            line?: number | null;
            /** Operation */
            operation?: string | null;
            /** Url */
            url?: string | null;
        };
        /** GuardResult */
        GuardResult: {
            /**
             * Checkedat
             * Format: date-time
             */
            checkedAt: string;
            /**
             * Findings
             * @description Where the guard failed; never a secret value.
             */
            findings: components["schemas"]["Finding"][];
            /**
             * Guard
             * @enum {string}
             */
            guard: "secrets" | "migrations" | "preview";
            /**
             * Reason
             * @description Stable code, translated by the console.
             */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "passed" | "failed";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /**
             * Repository
             * @example owner/name
             */
            repository: string;
        };
        /** JournalEntry */
        JournalEntry: {
            /** Actor */
            actor: string | null;
            /**
             * Actorkind
             * @enum {string}
             */
            actorKind: "person" | "agent" | "pono";
            /** Changenumber */
            changeNumber: number | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Headsha */
            headSha: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @example release.refused
             */
            kind: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
        };
        /** LocaleChoice */
        LocaleChoice: {
            /**
             * Locale
             * @enum {string}
             */
            locale: "fr" | "en";
        };
        /** Me */
        Me: {
            /**
             * Alertemailsenabled
             * @description False while the service has no mail server.
             */
            alertEmailsEnabled: boolean;
            /**
             * Chatalertsenabled
             * @description False while the service has no chat bot configured.
             */
            chatAlertsEnabled: boolean;
            /**
             * Chatlinked
             * @description True when the person linked a chat for quota alerts.
             */
            chatLinked: boolean;
            /** Codehostinstallurl */
            codeHostInstallUrl: string | null;
            /**
             * Email
             * @description Where quota alerts are sent; null when unknown.
             */
            email: string | null;
            /** Locale */
            locale: ("fr" | "en") | null;
            /** Login */
            login: string;
            /**
             * Organizationid
             * Format: uuid
             */
            organizationId: string;
            /**
             * Personid
             * Format: uuid
             */
            personId: string;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /**
             * Canrollback
             * @description False when production has no earlier successful deployment.
             */
            canRollback: boolean;
            /** Databasestatus */
            databaseStatus: ("found" | "missing" | "unknown") | null;
            /**
             * Environments
             * @description Production, development and the most recent preview only.
             */
            environments: components["schemas"]["Environment"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lastactivityat */
            lastActivityAt: string | null;
            lastDeployment: components["schemas"]["Deployment"] | null;
            /** Manifestproposalurl */
            manifestProposalUrl: string | null;
            /**
             * Manifeststatus
             * @enum {string}
             */
            manifestStatus: "present" | "proposed" | "absent";
            /** Name */
            name: string;
            /** Previews */
            previews: components["schemas"]["Environment"][];
            protection: components["schemas"]["Protection"];
            quota: components["schemas"]["Quota"] | null;
            /** Quotas */
            quotas: components["schemas"]["Quota"][];
            /** Refreshedat */
            refreshedAt: string | null;
            /** Repository */
            repository: string;
            /**
             * Stale
             * @description The last reading was incomplete; values date from refreshedAt.
             */
            stale: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "healthy" | "active" | "warning" | "failing" | "idle";
            /** Statereason */
            stateReason: string;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Databasestatus */
            databaseStatus: ("found" | "missing" | "unknown") | null;
            /**
             * Environments
             * @description Production, development and the most recent preview only.
             */
            environments: components["schemas"]["Environment"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lastactivityat */
            lastActivityAt: string | null;
            lastDeployment: components["schemas"]["Deployment"] | null;
            /**
             * Manifeststatus
             * @enum {string}
             */
            manifestStatus: "present" | "proposed" | "absent";
            /** Name */
            name: string;
            quota: components["schemas"]["Quota"] | null;
            /** Refreshedat */
            refreshedAt: string | null;
            /** Repository */
            repository: string;
            /**
             * Stale
             * @description The last reading was incomplete; values date from refreshedAt.
             */
            stale: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "healthy" | "active" | "warning" | "failing" | "idle";
            /** Statereason */
            stateReason: string;
        };
        /** Protection */
        Protection: {
            /** Branch */
            branch?: string | null;
            /** Checkedat */
            checkedAt?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "protected" | "unprotected" | "unavailable_on_plan" | "unknown";
        };
        /** Quota */
        Quota: {
            /**
             * Limit
             * @description Null when the provider does not state it.
             */
            limit: number | null;
            /**
             * Limitsource
             * @enum {string}
             */
            limitSource: "account_plan" | "free_tier_estimate";
            /**
             * Metric
             * @enum {string}
             */
            metric: "hosting_bandwidth_bytes" | "db_compute_seconds" | "db_storage_bytes" | "db_transfer_bytes";
            /** Ratio */
            ratio: number | null;
            /**
             * Readat
             * Format: date-time
             */
            readAt: string;
            /** Used */
            used: number;
        };
        /** Release */
        Release: {
            /** Approvedat */
            approvedAt: string | null;
            /** Approvedby */
            approvedBy: string | null;
            /** Author */
            author: string;
            /** Changenumber */
            changeNumber: number;
            /** Changeurl */
            changeUrl: string;
            /** Evaluatedat */
            evaluatedAt: string | null;
            /** Guards */
            guards: components["schemas"]["GuardResult"][];
            /** Headbranch */
            headBranch: string | null;
            /** Headsha */
            headSha: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Openedat
             * Format: date-time
             */
            openedAt: string;
            /**
             * State
             * @enum {string}
             */
            state: "open" | "merged" | "closed";
            /** Title */
            title: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "evaluating" | "refused" | "awaiting_approval" | "approved";
        };
        /** Repository */
        Repository: {
            /** Alreadyimported */
            alreadyImported: boolean;
            /** Defaultbranch */
            defaultBranch: string;
            /** Fullname */
            fullName: string;
            /**
             * Projectid
             * @description The project it already is, when imported.
             */
            projectId: string | null;
        };
        /** Rollback */
        Rollback: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Requestedat
             * Format: date-time
             */
            requestedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "succeeded" | "failed";
            /** Tocommit */
            toCommit: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Verdict */
        Verdict: {
            /**
             * Code
             * @example project.production_down
             */
            code: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
        };
        /** Workshop */
        Workshop: {
            /**
             * Counts
             * @description Number of projects per state, shown on each filter (FR-027).
             */
            counts: {
                [key: string]: number;
            };
            /** Projects */
            projects: components["schemas"]["ProjectSummary"][];
            /**
             * Verdicts
             * @description What needs a decision, shown before the list.
             */
            verdicts: components["schemas"]["Verdict"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_api_v1_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                pono_oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_connections_api_v1_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_api_v1_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_code_host_api_v1_connections_code_host_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_api_v1_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_chat_api_v1_me_chat_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_chat_api_v1_me_chat_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_chat_api_v1_me_chat_link_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_alert_address_api_v1_me_email_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAddress"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_locale_api_v1_me_locale_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocaleChoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_workshop_api_v1_projects_get: {
        parameters: {
            query?: {
                state?: ("healthy" | "active" | "warning" | "failing" | "idle") | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workshop"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_journal_api_v1_projects__project_id__journal_get: {
        parameters: {
            query?: {
                before?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_manifest_proposal_api_v1_projects__project_id__manifest_proposal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    protect_api_v1_projects__project_id__protection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Protection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_refresh_api_v1_projects__project_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_releases_api_v1_projects__project_id__releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_projects__project_id__releases__release_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                release_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_release_evaluation_api_v1_projects__project_id__releases__release_id__evaluation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                release_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_api_v1_projects__project_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rollback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_repositories_api_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pono_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
