/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as RuntimeOpenRouteImport } from './routes/runtime.open'
import { Route as WorkshopIndexRouteImport } from './routes/workshop/index'
import { Route as WorkshopConnectionsRouteImport } from './routes/workshop/connections'
import { Route as WorkshopImportRouteImport } from './routes/workshop/import'
import { Route as WorkshopProjectsProjectIdRouteImport } from './routes/workshop/projects.$projectId'
import { Route as WorkshopProjectsProjectIdJournalRouteImport } from './routes/workshop/projects.$projectId_.journal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeOpenRoute = RuntimeOpenRouteImport.update({
  id: '/runtime/open',
  path: '/runtime/open',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopIndexRoute = WorkshopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopConnectionsRoute = WorkshopConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopImportRoute = WorkshopImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopProjectsProjectIdRoute =
  WorkshopProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkshopRoute,
  } as any)
const WorkshopProjectsProjectIdJournalRoute =
  WorkshopProjectsProjectIdJournalRouteImport.update({
    id: '/projects/$projectId_/journal',
    path: '/projects/$projectId/journal',
    getParentRoute: () => WorkshopRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/runtime/open': typeof RuntimeOpenRoute
  '/workshop/connections': typeof WorkshopConnectionsRoute
  '/workshop/import': typeof WorkshopImportRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/workshop/projects/$projectId': typeof WorkshopProjectsProjectIdRoute
  '/workshop/projects/$projectId/journal': typeof WorkshopProjectsProjectIdJournalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/api/$': typeof ApiSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/runtime/open': typeof RuntimeOpenRoute
  '/workshop/connections': typeof WorkshopConnectionsRoute
  '/workshop/import': typeof WorkshopImportRoute
  '/workshop': typeof WorkshopIndexRoute
  '/workshop/projects/$projectId': typeof WorkshopProjectsProjectIdRoute
  '/workshop/projects/$projectId/journal': typeof WorkshopProjectsProjectIdJournalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/runtime/open': typeof RuntimeOpenRoute
  '/workshop/connections': typeof WorkshopConnectionsRoute
  '/workshop/import': typeof WorkshopImportRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/workshop/projects/$projectId': typeof WorkshopProjectsProjectIdRoute
  '/workshop/projects/$projectId_/journal': typeof WorkshopProjectsProjectIdJournalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/privacy'
    | '/workshop'
    | '/api/$'
    | '/oauth/consent'
    | '/runtime/open'
    | '/workshop/connections'
    | '/workshop/import'
    | '/workshop/'
    | '/workshop/projects/$projectId'
    | '/workshop/projects/$projectId/journal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/privacy'
    | '/api/$'
    | '/oauth/consent'
    | '/runtime/open'
    | '/workshop/connections'
    | '/workshop/import'
    | '/workshop'
    | '/workshop/projects/$projectId'
    | '/workshop/projects/$projectId/journal'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/privacy'
    | '/workshop'
    | '/api/$'
    | '/oauth/consent'
    | '/runtime/open'
    | '/workshop/connections'
    | '/workshop/import'
    | '/workshop/'
    | '/workshop/projects/$projectId'
    | '/workshop/projects/$projectId_/journal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  PrivacyRoute: typeof PrivacyRoute
  WorkshopRoute: typeof WorkshopRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  OauthConsentRoute: typeof OauthConsentRoute
  RuntimeOpenRoute: typeof RuntimeOpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/open': {
      id: '/runtime/open'
      path: '/runtime/open'
      fullPath: '/runtime/open'
      preLoaderRoute: typeof RuntimeOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/': {
      id: '/workshop/'
      path: '/'
      fullPath: '/workshop/'
      preLoaderRoute: typeof WorkshopIndexRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/connections': {
      id: '/workshop/connections'
      path: '/connections'
      fullPath: '/workshop/connections'
      preLoaderRoute: typeof WorkshopConnectionsRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/import': {
      id: '/workshop/import'
      path: '/import'
      fullPath: '/workshop/import'
      preLoaderRoute: typeof WorkshopImportRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/projects/$projectId': {
      id: '/workshop/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workshop/projects/$projectId'
      preLoaderRoute: typeof WorkshopProjectsProjectIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/projects/$projectId_/journal': {
      id: '/workshop/projects/$projectId_/journal'
      path: '/projects/$projectId/journal'
      fullPath: '/workshop/projects/$projectId/journal'
      preLoaderRoute: typeof WorkshopProjectsProjectIdJournalRouteImport
      parentRoute: typeof WorkshopRoute
    }
  }
}

interface WorkshopRouteChildren {
  WorkshopConnectionsRoute: typeof WorkshopConnectionsRoute
  WorkshopImportRoute: typeof WorkshopImportRoute
  WorkshopIndexRoute: typeof WorkshopIndexRoute
  WorkshopProjectsProjectIdRoute: typeof WorkshopProjectsProjectIdRoute
  WorkshopProjectsProjectIdJournalRoute: typeof WorkshopProjectsProjectIdJournalRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopConnectionsRoute: WorkshopConnectionsRoute,
  WorkshopImportRoute: WorkshopImportRoute,
  WorkshopIndexRoute: WorkshopIndexRoute,
  WorkshopProjectsProjectIdRoute: WorkshopProjectsProjectIdRoute,
  WorkshopProjectsProjectIdJournalRoute: WorkshopProjectsProjectIdJournalRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  PrivacyRoute: PrivacyRoute,
  WorkshopRoute: WorkshopRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  OauthConsentRoute: OauthConsentRoute,
  RuntimeOpenRoute: RuntimeOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
